=== nktumu/vps-backend-master-8a127b8ba61/json_data/schemas/async_size_response.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "async_size_response.json",
    "title": "Asyncronous Size Response",
    "description": "JSON schema for the primary sizing request response (new Asyncronous API)",
    "type": "object",
    "required": [
        "job_id",
        "tasks"
    ],
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "$ref": "util.json#/$defs/$schema"
        },
        "job_id": {
            "type": "string",
            "format": "uuid",
            "description": "Unique ID for each Sizing request.  Generated by the sizing API request, returned to the client in the first response. Client is required to provide this value when subsequently requesting status."
        },
        "tasks": {
            "type": "array",
            "description": "List of task fstatus objects.  One object for each unique task that is exposed to the client.  Client is expected to use this data for live progress reporting.",
            "items": {
                "type": "object",
                "required": [
                    "task",
                    "status",
                    "progress"
                ],
                "properties": {
                    "task": {
                        "type": "string",
                        "description": "Name of the unique task"
                    },
                    "status": {
                        "type": "string",
                        "enum": [
                            "PENDING",
                            "IN_PROGRESS",
                            "COMPLETE",
                            "ERROR"
                        ]
                    },
                    "progress": {
                        "type": "integer",
                        "minimum": 0,
                        "maximum": 100
                    },
                    "error_code": {
                        "type": "integer"
                    },
                    "error_msg": {
                        "type": "string"
                    }
                },
                "oneOf": [
                    {
                        "properties": {
                            "status": {
                                "const": "PENDING"
                            },
                            "progress": {
                                "const": 0,
                                "type": "integer"
                            }
                        }
                    },
                    {
                        "properties": {
                            "status": {
                                "const": "IN_PROGRESS"
                            },
                            "progress": {
                                "minimum": 1,
                                "maximum": 99
                            }
                        }
                    },
                    {
                        "properties": {
                            "status": {
                                "const": "COMPLETE"
                            },
                            "progress": {
                                "const": 100
                            }
                        }
                    },
                    {
                        "properties": {
                            "status": {
                                "const": "ERROR"
                            }
                        },
                        "required": [
                            "error_code",
                            "error_msg"
                        ]
                    }
                ]
            }
        },
        "workload_results": {
            "type": "array",
            "description": "Results from initial workload evaluation"
        },
        "appliance_results": {
            "$ref": "size_response.json"
        }
    }
}

=== nktumu/vps-backend-master-8a127b8ba61/json_data/example_responses/sizing_complete.json
{
    "$schema": "../schemas/async_size_response.json",
    "job_id": "88888888-4444-4444-4444-cccccccccccc",
    "tasks": [
        {
            "task": "workload_sizing",
            "status": "COMPLETE",
            "progress": 100
        },
        {
            "task": "appliance_sizing",
            "status": "COMPLETE",
            "progress": 100
        }
    ],
    "workload_results": [
        {
            "example": "results go here"
        }
    ],
    "appliance_results": {
        "$schema": "../schemas/async_size_response.json",
        "site_assignments": [],
        "horizon": {
            "num_years": 1,
            "planning_year": 1
        },
        "windows": {
            "full_backup_hours": 0,
            "incremental_backup_hours": 0,
            "replication_hours": 0
        }
    }
}
