=== nktumu/vps-backend-master-8a127b8ba61/json_data/schemas/workload_type.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "workload_type.json",
    "title": "Workload Type",
    "description": "Defines a Workload Type. All Workload Type definitions, either preset or user defined, must match this format.",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "addl_full_dedup_rate": {
            "description": "Dedup rate for additional full backups.  This is a percentage value expressed in decimal (0.1 -> 10%, etc.)",
            "type": "number"
        },
        "annual_growth_rate": {
            "description": "Year-over-year growth rate of FETB.  This is a percentage value expressed in decimal (0.1 -> 10%, etc.)",
            "type": "number"
        },
        "daily_change_rate": {
            "description": "Daily change rate.  This is a percentage value expressed in decimal (0.1 -> 10%, etc.)",
            "type": "number"
        },
        "dedup_rate": {
            "description": "Dedup rate.  This is a percentage value expressed in decimal (0.1 -> 10%, etc.)",
            "type": "number"
        },
        "files_per_channel": {
            "type": "number"
        },
        "initial_dedup_rate": {
            "description": "Initial dedup rate.  This is a percentage value expressed in decimal (0.1 -> 10%, etc.)",
            "type": "number"
        },
        "log_backup_capable": {
            "description": "Whether this workload type is able to do log backups.",
            "type": "boolean"
        },
        "name": {
            "description": "Name of workload type.",
            "type": "string"
        },
        "num_channels": {
            "type": "integer"
        },
        "num_files": {
            "type": "integer"
        }
    },
    "required": [
        "addl_full_dedup_rate",
        "annual_growth_rate",
        "daily_change_rate",
        "dedup_rate",
        "files_per_channel",
        "initial_dedup_rate",
        "log_backup_capable",
        "name",
        "num_channels",
        "num_files"
    ]
}

=== nktumu/vps-backend-master-8a127b8ba61/json_test_data/workload_types/file-typical.json
{
    "name": "File System (Typical)",
    "annual_growth_rate": 0.2,
    "daily_change_rate": 0.05,
    "initial_dedup_rate": 0.75,
    "dedup_rate": 0.85,
    "addl_full_dedup_rate": 0.95,
    "num_files": 3000000,
    "num_channels": 0,
    "files_per_channel": 1,
    "log_backup_capable": false
}

=== nktumu/vps-backend-master-8a127b8ba61/json_test_data/workload_types/file-small.json
{
    "name": "File System (Small Files)",
    "annual_growth_rate": 0.2,
    "daily_change_rate": 0.05,
    "initial_dedup_rate": 0.75,
    "dedup_rate": 0.85,
    "addl_full_dedup_rate": 0.95,
    "num_files": 100000000,
    "num_channels": 0,
    "files_per_channel": 1,
    "log_backup_capable": false
}
